name: Desplegar sitio web en AWS S3 Y CloudFront

on:
    push:
        branches:
        - main # Ejecutar el despliegue cuando se haga un push a la rama main


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to S3
              run: echo "Deploying to S3"


      
